# Generated by Django 5.0.1 on 2024-04-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='account',
        ),
    ]
