# Generated by Django 5.0.1 on 2024-04-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_useraccount_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user',
            new_name='account',
        ),
    ]
