# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
